Add event connections to attendees types.
the-events-calendar/ql-events pull request #29
Opened 2020-12-31 02:55 UTC by justlevine

Adds event connections to the various attendee types. Closes #24 .

1. The `Event` type has `rSVPAttendees`, `payPalAttendees`, and `wooAttendees`.
2. `rSVPAttendees`, `payPalAttendees`, and `wooAttendees` can now be filtered by `where : { eventsIn: $id }`.

Note:
- Separate `class-{type}attendee.php` and `class-{type}attendee-resolver.php` files were created for each attendee type. This isn't very DRY, but was the best I could do without fully changing attendee over to an `interface`.
- The old `class-attendee-resolver.php` was never actually included before. There's [a code segment](https://github.com/simplur/ql-events/blob/66125f4a32afad5f60e0ee2c438967802e4a5bbc/includes/data/connection/class-attendee-connection-resolver.php#L37) from @kidunot89 that I left in, because I'm not really sure of the purpose/its effect. If it isn't necessary, it should be removed.
- For some reason, `composer dump-autoload` was generating `platform_check.php`. I manually removed it, but to be safe, a maintainer should probably regenerate the autoload.

2021-04-09 02:29 UTC, bordoni requested changes
Suggested a couple small things.

2021-04-09 02:29 UTC, bordoni commented on includes/class-core-schema-filters.php
> +				),
```suggestion
				[
					'\WPGraphQL\QL_Events\Data\Connection\PayPalAttendee_Connection_Resolver',
					'get_query_args',
				],
```

2021-04-09 02:29 UTC, bordoni commented on includes/class-core-schema-filters.php
> +		);
```suggestion
			add_filter( 'graphql_input_fields', [ __CLASS__, 'attendees_where_args' ], 10, 2 );
```

2021-04-09 02:29 UTC, bordoni commented on includes/class-core-schema-filters.php
> +				),
```suggestion
				[
					'\WPGraphQL\QL_Events\Data\Connection\WooAttendee_Connection_Resolver',
					'get_query_args',
				],
```

2021-04-09 02:29 UTC, bordoni commented on includes/class-core-schema-filters.php
> +				array( __CLASS__, 'ticket_plus_attendees_where_args' ),
```suggestion
				[ __CLASS__, 'ticket_plus_attendees_where_args' ],
```

2021-04-09 02:29 UTC, bordoni commented on includes/connection/class-paypalattendees.php
> +				)
```suggestion
				[
					'fromType'      => 'Event',
					'toType'        => 'PayPalAttendee',
					'fromFieldName' => 'payPalAttendees',
				]
```

2021-04-09 02:29 UTC, bordoni commented on includes/connection/class-rsvpattendees.php
> +					'fromFieldName' => 'rSVPAttendees',
Is this `r` lower case intentional?

2021-04-09 02:29 UTC, bordoni commented on includes/connection/class-wooattendees.php
> +				)
```suggestion
				[
					'fromType'      => 'Event',
					'toType'        => 'WooAttendee',
					'fromFieldName' => 'wooAttendees',
				]
```

2021-04-09 02:29 UTC, bordoni commented on includes/connection/class-wooattendees.php
> +		);
```suggestion
		return [
			'eventsIn' => [
				'type' => [ 'list_of' => 'ID' ],
				'description' => __( 'Filter the connection based on event Id', 'ql-events' ),
			]
		];
```

2021-04-09 02:29 UTC, bordoni commented on includes/data/connection/class-paypalattendee-connection-resolver.php
> +						);
```suggestion
						$query_args['meta_query'][] = [
							'key'     => PAYPAL::ATTENDEE_EVENT_KEY,
							'value'   => $source->ID,
							'compare' => '=',
						];
```

2021-04-09 02:29 UTC, bordoni commented on includes/data/connection/class-paypalattendee-connection-resolver.php
> +							$query_args['meta_query'] = array(); // WPCS: slow query ok.
```suggestion
							$query_args['meta_query'] = []; // WPCS: slow query ok.
```

2021-04-09 02:29 UTC, bordoni commented on includes/connection/class-rsvpattendees.php
> +		);
```suggestion
		return [
			'eventsIn' => [
				'type' => [ 'list_of' => 'ID' ],
				'description' => __( 'Filter the connection based on event Id', 'ql-events' ),
			]
		];
```

2021-04-10 03:20 UTC, justlevine commented
Requested changes merged.

2023-03-24 21:24 UTC, kidunot89 commented
@justlevine @bordoni This functionality was implemented in #46

2023-03-24 21:24 UTC, closed without merging