feat: Custom ticket field types and queries implemented.
the-events-calendar/ql-events pull request #40
Opened 2022-02-01 01:42 UTC by kidunot89

# Summary
- Adds **TicketField** Interface to schema
- Adds the following **TicketField** child object type
  - **TicketFieldBirthdate**
  - **TicketFieldCheckbox**
  - **TicketFieldDate**
  - **TicketFieldDropdown**
  - **TicketFieldEmail**
  - **TicketFieldPhone**
  - **TicketFieldRadio**
  - **TicketFieldText**
  - **TicketFieldURL**
- Adds the `ticketFields` field to the **Product** type
__Example Query__
```graphql
{
  events {
    nodes {
      wooTickets {
        nodes {
          name
          ticketFields {
            type
            label
            description
            required
            ... on TicketFieldCheckbox {
              options
            }
            ... on TicketFieldDropdown {
              options
            }
            ... on TicketFieldEmail {
              placeholder
            }
            ... on TicketFieldPhone {
              placeholder
            }
            ... on TicketFieldRadio {
              options
            }
            ... on TicketFieldText {
              placeholder
            }
            ... on TicketFieldURL {
              placeholder
            }
          }
        }
      }
    }
  }
}
```
- Adds the `ticketFields` field to the **Event**
__Example Query__
```
{
  events {
    nodes {
      ticketFields {
        type
        label
        description
        required
        ... on TicketFieldCheckbox {
          options
        }
        ... on TicketFieldDropdown {
          options
        }
        ... on TicketFieldEmail {
          placeholder
        }
        ... on TicketFieldPhone {
          placeholder
        }
        ... on TicketFieldRadio {
          options
        }
        ... on TicketFieldText {
          placeholder
        }
        ... on TicketFieldURL {
          placeholder
        }
      }
    }
  }
}
```

2022-02-03 19:20 UTC, borkweb requested changes
This is looking pretty great! Just a couple of minor tweaks.

2022-02-03 19:20 UTC, borkweb commented on includes/class-type-registry.php
> +			\WPGraphQL\QL_Events\Type\WPObject\Ticket_Field\URL::register();
We could simplify this down to the following, due to the namespace at the top of the file:

```suggestion
			Type\WPInterface\Ticket_Field::register_type();
			Type\WPObject\Ticket_Field\Birthdate::register();
			Type\WPObject\Ticket_Field\Checkbox::register();
			Type\WPObject\Ticket_Field\Date::register();
			Type\WPObject\Ticket_Field\Dropdown::register();
			Type\WPObject\Ticket_Field\Email::register();
			Type\WPObject\Ticket_Field\Phone::register();
			Type\WPObject\Ticket_Field\Radio::register();
			Type\WPObject\Ticket_Field\Text::register();
			Type\WPObject\Ticket_Field\URL::register();
```

2022-02-03 19:20 UTC, borkweb commented on includes/class-type-registry.php
> +			\WPGraphQL\QL_Events\Type\WPObject\Ticket_Field\URL::register();
Or even add `use WPGraphQL\QL_Events\Type\WPObject\Ticket_Field;` at the top then change to:

```suggestion
			Ticket_Field::register_type();
			Ticket_Field\Birthdate::register();
			Ticket_Field\Checkbox::register();
			Ticket_Field\Date::register();
			Ticket_Field\Dropdown::register();
			Ticket_Field\Email::register();
			Ticket_Field\Phone::register();
			Ticket_Field\Radio::register();
			Ticket_Field\Text::register();
			Ticket_Field\URL::register();
```

2022-02-03 19:20 UTC, borkweb commented on includes/types/interface/class-ticket-field.php
> +			array(
Can we switch to short array syntax? `[]` rather than `array()`?

2022-02-03 19:20 UTC, borkweb commented on includes/types/object/class-ticket-fieldset-types.php
> +			print_r( $fieldset );
Remove this debug line. 🕺

2022-02-03 19:20 UTC, borkweb commented on includes/types/object/class-ticket-fieldset-types.php
> +						// )
Remove?

2022-10-05 23:43 UTC, bordoni approved these changes

2022-10-11 18:41 UTC, borkweb approved these changes

2022-10-11 18:43 UTC, merged