Attendee interface/connections/mutations added. Order interface added.
the-events-calendar/ql-events pull request #46
Opened 2022-06-16 06:03 UTC by kidunot89

# Summary
- Adds `Attendee` Interface type along with the `attendee` connections from `RootQuery` and `Event`.
- Adds `OrderInterface` _(Couldn't rename WooGraphQL's **Order** type)_ interface type.
- Adds Attendee `data` field for query attendee meta.

# TODO
- Add attendee mutations.
  - `registerAttendee`
  - `registerWooAttendee`
  - `updateAttendee`
  - `updateAttendeeMeta`
  - `deleteAttendee`

2022-10-05 16:46 UTC, bordoni requested changes
Small things, the only consideration is that if we are going towards PHP 7.4, we should think about type hinting.

2022-10-05 16:46 UTC, bordoni commented on includes/types/interface/class-attendee-interface.php
> +					) : null;
This is a little bit weird to read. Mind creating a return to `null` otherwise, return the callback.

2022-10-05 16:46 UTC, bordoni commented on includes/mutation/class-register-attendee.php
> +				'mutateAndGetPayload' => self::mutate_and_get_payload(),
static instead of self on these?

2022-10-05 16:46 UTC, bordoni commented on includes/connection/class-attendees.php
> +		return self::get_connection_args( [], $attendee_type );
Static instead of self?

2022-10-05 16:46 UTC, bordoni commented on includes/connection/class-attendees.php
> +						[ __CLASS__, 'get_attendee_type_connection_args' ],
Maybe?
```suggestion
						[ static::class, 'get_attendee_type_connection_args' ],
```

2022-10-05 16:46 UTC, bordoni commented on includes/connection/class-attendees.php
> +						[ __CLASS__, 'get_attendee_type_connection_args' ],
maybe?
```suggestion
						[ static::class, 'get_attendee_type_connection_args' ],
```

2022-10-06 00:16 UTC, kidunot89 commented on includes/mutation/class-register-attendee.php
> +				'mutateAndGetPayload' => self::mutate_and_get_payload(),
@bordoni I understand the reasoning, but don't agree. Making this changeable with `static` would encourage extending this class directly and that's not the recommended way of extending/replacing the logic. Utilizing the hooks inside of the resolver and the `de/register_graphql*()` functions are. This is a consistency measure that is maintained across most of the widely used WPGraphQL extensions.

2022-10-06 00:18 UTC, kidunot89 commented on includes/connection/class-attendees.php
> +		return self::get_connection_args( [], $attendee_type );
Same as above, I don't want to encourage the extension/inheritance of this class.

2022-10-06 00:19 UTC, kidunot89 commented on includes/connection/class-attendees.php
> +						[ __CLASS__, 'get_attendee_type_connection_args' ],
Same as above

2022-10-11 19:00 UTC, kidunot89 commented on includes/types/interface/class-attendee-interface.php
> +					) : null;
Agreed. A lot of this logic isn't used because the attendee post type isn't public

2022-10-11 19:02 UTC, kidunot89 commented on includes/types/interface/class-attendee-interface.php
> +					) : null;
I've changed the logic to this
```php
return absint( $post_id )
		? $context->get_loader( 'post' )->load_deferred( $post_id )->then(
			function ( $post ) use ( $post_type_object ) {

				// if the post isn't an instance of a Post model, return
				if ( ! $post instanceof Post ) {
					return null;
				}

				return $post;
			}
		)
		: null;
},
```

2022-10-14 01:48 UTC, bordoni approved these changes

2022-10-19 12:06 UTC, bordoni approved these changes

2022-12-06 14:19 UTC, merged