feat: QL Events settings tab added and schema organized
the-events-calendar/ql-events pull request #55
Opened 2023-04-24 23:49 UTC by kidunot89

# Summary
- Adds the QL Events settings tab.
- Restructures schema so missing dependency plugins not required by the schema won't cause an error.

2023-04-26 01:29 UTC, bordoni requested changes
Two small comments, and double checking why are we using so much Anonymous functions? Instead of creating a new method, for example on `ql_events_resolve_tec_order_type` and so many others. It's ok, just wanted to understand why.

2023-04-26 01:29 UTC, bordoni commented on includes/admin/class-general.php
> +		$test_mode_status = (bool) defined( 'QL_EVENTS_TEST_MODE' ) && QL_EVENTS_TEST_MODE ? 'force enabled' : 'force disabled';
I wounder if we should have a method for the test mode verification.

2023-04-26 02:28 UTC, kidunot89 commented
> Two small comments, and double checking why are we using so much Anonymous functions? Instead of creating a new method, for example on `ql_events_resolve_tec_order_type` and so many others. It's ok, just wanted to understand why.

Cuz I was rushing lol

2023-05-26 03:35 UTC, bordoni requested changes
Minor things and some questions, would love to see us having `@since TBD` in general.

And replace all TBDs right before launch with the version.

2023-05-26 03:35 UTC, bordoni commented on includes/types/object/class-wooattendee-type.php
> +					},
Not for this PR, but I would love to see us move towards having the actual method live in this class, and we pass it as a `Callable` here. Feels  like it would be better for long term unit testing and readability.

2023-05-26 03:35 UTC, bordoni commented on includes/types/object/class-wooattendee-type.php
> +			[ __CLASS__, 'resolve_woo_attendee' ],
I wonder why not?
```suggestion
			[ static::class, 'resolve_woo_attendee' ],
```

2023-05-26 03:35 UTC, bordoni commented on includes/types/interface/class-ticket-interface.php
> +							$type = apply_filters( 'ql_events_resolve_ticket_type', null, $value );
Docblock missing here.

2023-05-26 03:35 UTC, bordoni commented on includes/types/interface/class-order-interface.php
> +							$type = apply_filters( 'ql_events_resolve_tec_order_type', null, $value );
Docblock missing here.

2023-05-26 03:35 UTC, bordoni commented on includes/types/interface/class-attendee-interface.php
> +							$type = apply_filters( 'ql_events_resolve_attendee_type', null, $value );
Docblock missing here.

2023-05-26 03:35 UTC, bordoni commented on includes/connection/class-tickets.php
> +			 * @param array       $ticket_classes - TEC ticket class names.
It would be cool to see some `@since TBD` in the docblocks.

2023-05-26 04:18 UTC, kidunot89 commented on includes/types/object/class-wooattendee-type.php
> +					},
What method are you referring to?

2023-05-26 04:36 UTC, bordoni commented on includes/types/object/class-wooattendee-type.php
> +					},
To the actual function that is assigned to the 'resolve' key, I would love for us to go towards using methods from this class, instead of anonymous functions. Which will make the code harder to test and read down the line.

2023-05-26 14:30 UTC, merged